app: MyQuirkyBot
service: svl

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    MONGO_PASSWORD: ${env:MONGO_PASSWORD}

functions:
  cron:
    handler: handler.send_message
    events:
      # Invoke Lambda function at 12:15 UTC every day
      - schedule: cron(15 12 * * ? *)